# Generated by Django 6.0.4 on 2026-04-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default=':)', null=True),
        ),
    ]
