# Generated by Django 6.0.4 on 2026-04-18 22:57

import django.core.validators
import rar.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rar', '0003_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/files/', validators=[rar.utils.validators.file_sizz_lool_haha_python_manage_py_spirits_under_my_eyes, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'zip', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/images/', validators=[rar.utils.validators.imig_sisze_lol_blab_blud_bluadb_pip_install_penguin_py, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
