# Generated by Django 6.0.4 on 2026-04-18 23:23

import django.core.validators
import rar.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rar', '0004_alter_photo_file_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/images/', validators=[rar.utils.validators.imig_sisze_lol_blab_blud_bluadb_pip_install_penguin_py, rar.utils.validators.paicture_demention_core, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
